apiVersion: batch/v1
kind: Job
metadata:
  name: bd-wbte-job
spec:
  template:
    spec:
      containers:
      - name: bd-wbte-job
        image: yash5090/bd-wbte:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
